repos:
  - repo: local
    hooks:
      - id: poetry-ruff-check
        name: Run ruff check
        entry: poetry run ruff check
        language: python
        types: [python]
        files: \.py$
      - id: poetry-ruff-format
        name: Run ruff format
        entry: poetry run ruff format
        language: python
        types: [python]
        files: \.py$