BEGIN TRANSACTION;
DROP TABLE IF EXISTS "fund_holdings";
CREATE TABLE IF NOT EXISTS "fund_holdings" (
	"FUND"	TEXT,
	"DATE"	TEXT,
	"FINANCIAL_TYPE" TEXT,
	"SYMBOL"	TEXT,
	"SECURITY_NAME"	TEXT,
	"SEDOL"	TEXT,
	"ISIN"	TEXT,
	"PRICE"	REAL,
	"QUANTITY"	REAL,
	"REALISED_P_L"	REAL,
	"MARKET_VALUE"	REAL
);
COMMIT;
