name: commit

on: 
  pull_request:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Poetry 2.1.3
        run: |
          pip install poetry==2.1.3
      - name: Install Dependencies
        run: |
          poetry config virtualenvs.create false
          poetry install
      - name: Run pytest
        run: |
          poetry run pytest